code --install-extension asvetliakov.vscode-neovim
code --install-extension bmewburn.vscode-intelephense-client
code --install-extension dbaeumer.vscode-eslint
code --install-extension gruntfuggly.todo-tree
code --install-extension llvm-vs-code-extensions.lldb-dap
code --install-extension ms-azuretools.vscode-containers
code --install-extension ms-python.debugpy
code --install-extension ms-python.python
code --install-extension ms-python.vscode-pylance
code --install-extension ms-python.vscode-python-envs
code --install-extension ms-vscode-remote.remote-containers
code --install-extension ms-vscode.cmake-tools
code --install-extension ms-vscode.cpp-devtools
code --install-extension ms-vscode.cpptools
code --install-extension ms-vscode.cpptools-extension-pack
code --install-extension ms-vscode.cpptools-themes
code --install-extension murloccra4ler.leap
code --install-extension pkief.material-icon-theme
code --install-extension redhat.java
code --install-extension shevaua.phpcs
code --install-extension swiftlang.swift-vscode
code --install-extension twxs.cmake
code --install-extension vscjava.vscode-gradle
code --install-extension vscjava.vscode-java-debug
code --install-extension vscjava.vscode-java-dependency
code --install-extension vscjava.vscode-java-pack
code --install-extension vscjava.vscode-java-test
code --install-extension vscjava.vscode-maven
code --install-extension yatki.vscode-surround
