code --install-extension stevenc1.adddoccomments
code --install-extension amazonwebservices.aws-toolkit-vscode
code --install-extension danielthielking.aws-cloudformation-yaml
code --install-extension bungcip.better-toml
code --install-extension ms-vscode.cpptools
code --install-extension kddejong.vscode-cfn-lintu
code --install-extension kisstkondoros.vscode-codemetrics
code --install-extension ms-azuretools.vscode-docker
code --install-extension dbaeumer.vscode-eslint
code --install-extension waderyan.gitblame
code --install-extension donjayamanne.githistory
code --install-extension oderwat.indent-rainbow
code --install-extension atlassian.atlascode
code --install-extension ms-vscode.powershell
code --install-extension esbenp.prettier-vscode
code --install-extension alefragnani.project-manager
code --install-extension ms-python.python
code --install-extension ms-vscode-remote.remote-wsl
code --install-extension rust-lang.rust-analyzer
code --install-extension ban.spellright
code --install-extension asvetliakov.vscode-neovim
code --install-extension redhat.vscode-yaml
